[BXMSPROD-944] build chain configuration
apache/incubator-kie-kogito-pipelines pull request #158
Opened 2021-04-30 09:26 UTC by Ginxo

https://issues.redhat.com/browse/BXMSPROD-944

2021-04-30 09:31 UTC, radtriste commented on .ci/pull-request-config.yaml
> +        mvn -f kogito-runtimes/pom.xml clean install -fae -Prun-code-coverage -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
we don't have sonarcloud import here ?

2021-04-30 09:31 UTC, radtriste commented on .ci/pull-request-config.yaml
> +      current: mvn -f optaplanner/pom.xml -e clean install -nsu -Prun-code-coverage,wildfly -Dfull  -Dintegration-tests=false -Dmaven.test.failure.ignore=true -Dmaven.wagon.httpconnectionManager.ttlS
same for sonarcloud

2021-04-30 09:31 UTC, radtriste commented on .ci/pull-request-config.yaml
> +        mvn -f kogito-apps/pom.xml clean install -Prun-code-coverage -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
same for sonarcloud

2021-04-30 11:54 UTC, Ginxo commented on .ci/pull-request-config.yaml
> +        mvn -f kogito-runtimes/pom.xml clean install -fae -Prun-code-coverage -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
can you please propose change? @radtriste

2021-04-30 11:59 UTC, radtriste commented on .ci/pull-request-config.yaml
> +        mvn -f kogito-runtimes/pom.xml clean install -fae -Prun-code-coverage -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
ok so first are we able to upload sonarcloud info from GHA ? depending on the answer, I will update the file

2021-04-30 12:15 UTC, danielezonca commented
@radtriste 
I'm not sure we want add sonarcloud to GHA, that part is already covered by Jenkins while this pipeline is mainly to have a fallback.
I think we can remove sonarcloud/run-code-coverage here, wdyt?

2021-04-30 12:34 UTC, radtriste commented
That was my point yes, if no sonarcloud then we can get rid of the `run-code-coverage` profile :)

2021-05-03 06:40 UTC, Ginxo commented on .ci/pull-request-config.yaml
> +        mvn -f kogito-runtimes/pom.xml clean install -fae -Prun-code-coverage -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
@radtriste yes we are (thanks to this `pull_request_target` event we are able to get secrets from forked projects) but I would try to avoid it since the taken value can easily exposed....

2021-05-03 06:40 UTC, Ginxo commented
> That was my point yes, if no sonarcloud then we can get rid of the `run-code-coverage` profile :)

@radtriste @danielezonca confirm this please

2021-05-03 07:46 UTC, radtriste requested changes

2021-05-03 07:46 UTC, radtriste commented on .ci/pull-request-config.yaml
> +        mvn -f kogito-runtimes/pom.xml clean install -fae -Prun-code-coverage -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
```suggestion
        mvn -f kogito-runtimes/pom.xml clean install -fae -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
```

2021-05-03 07:46 UTC, radtriste commented on .ci/pull-request-config.yaml
> +        mvn clean install -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -DskipTests
for readibility

```suggestion
        mvn clean install -DskipTests -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
```

2021-05-03 07:46 UTC, radtriste commented on .ci/pull-request-config.yaml
> +        mvn clean install -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -DskipTests
btw @Ginxo would there be a way to have `-Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3` in `MAVEN_OPTS` env variable ?
that would make the config more readable as well as this is a recurrent option

2021-05-03 07:46 UTC, radtriste commented on .ci/pull-request-config.yaml
> +        mvn -f kogito-runtimes-integration-tests/pom.xml -fae -Ppersistence clean verify
For consistency

```suggestion
        mvn -f kogito-runtimes-integration-tests/pom.xml -fae clean verify -Ppersistence
```

2021-05-03 07:46 UTC, radtriste commented on .ci/pull-request-config.yaml
> +        mvn -f kogito-runtimes/pom.xml clean install -fae -Prun-code-coverage -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
ok let's remove it from there

2021-05-03 07:46 UTC, radtriste commented on .ci/pull-request-config.yaml
> +      current: mvn -f optaplanner/pom.xml -e clean install -nsu -Prun-code-coverage,wildfly -Dfull  -Dintegration-tests=false -Dmaven.test.failure.ignore=true -Dmaven.wagon.httpconnectionManager.ttlS
```suggestion
      current: mvn -f optaplanner/pom.xml -e -nsu clean install -Dfull  -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
```

2021-05-03 07:46 UTC, radtriste commented on .ci/pull-request-config.yaml
> +        mvn -f kogito-apps/pom.xml clean install -Prun-code-coverage -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
```suggestion
        mvn -f kogito-apps/pom.xml clean install -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
```

2021-05-03 07:47 UTC, radtriste commented
@Ginxo @danielezonca can one of you check the proposed changes and batch commit them if ok ?

2021-05-03 08:12 UTC, danielezonca commented on .ci/pull-request-config.yaml
> +        mvn clean install -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -DskipTests
@Ginxo linked me [this issue](https://github.com/actions/virtual-environments/issues/1499) so probably it is better to use
`-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120`

2021-05-03 08:13 UTC, danielezonca commented
@radtriste done

2021-05-03 10:48 UTC, Ginxo commented on .ci/pull-request-config.yaml
> +        mvn clean install -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -DskipTests
@radtriste @danielezonca I see two options here:

- To use `.mvn/maven.config` file to define those flags. (it will affect to every community developer)
- To define a secret like MVN_OPTS and use it from the flow like `${{ secrets.MVN_OPTS }}`
- We could define a default command like `echo $MVN_OPTS=-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120` and then use the MVN_OPTS variable from every maven command (it will require merge mechanism for every project definition (it will mesh up the configuration a bit)

Do you any additional possibility? I would keep it as it is, wdyt?

2021-05-03 10:51 UTC, danielezonca commented on .ci/pull-request-config.yaml
> +        mvn clean install -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -DskipTests
Personally I would prefer the last one. Even if it adds some noise in the configuration but it is definitely more easier to read/change compared to a GitHub secret

2021-05-03 11:57 UTC, radtriste commented on .ci/pull-request-config.yaml
> +        mvn clean install -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -DskipTests
couldn't we just set in the GHAction yaml file and env variable for the whole use node ?

2021-05-05 13:31 UTC, radtriste approved these changes

2021-05-07 08:50 UTC, danielezonca approved these changes

2021-05-07 09:20 UTC, merged