KOGITO-5627 Added LTS native image builder
apache/incubator-kie-kogito-pipelines pull request #229
Opened 2021-08-02 11:40 UTC by radtriste

2021-08-03 06:23 UTC, Ginxo requested changes
I'm ok with the change, but it looks more like a testing stuff than a final change...

2021-08-03 06:23 UTC, Ginxo commented on dsl/seed/config/branch.yaml
> +  # - name: kogito-apps
why don't you remove these lines? is it for testing purposes?

2021-08-03 06:23 UTC, Ginxo commented on dsl/seed/config/main.yaml
> +  - kogito-5627
I guess this is for testing purposes... :thinking:

2021-08-03 06:23 UTC, Ginxo commented on dsl/seed/jobs/seed_job_main.groovy
> +        stringParam('SEED_AUTHOR', 'radtriste', 'If different from the default')
testing?

2021-08-03 06:23 UTC, Ginxo commented on dsl/seed/config/branch.yaml
> +    name: radtriste
testing? (the same for the rest of the `radtriste` changes in this file)

2021-08-03 06:23 UTC, Ginxo commented on dsl/seed/jobs/seed_job_main.groovy
> +        stringParam('SEED_BRANCH', 'test-setup', 'If different from the default')
testing?

2021-08-03 06:58 UTC, radtriste commented
@Ginxo yeah sorry, forgot to remove the test commit ... will update native job of OP, Apps and Examples and test the jobs and then will remove. I let you know

2021-08-04 09:11 UTC, Ginxo approved these changes
LGTM

2021-08-05 07:46 UTC, merged