[1.11.x] PLANNER-2474 optaplanner CI (#215)
apache/incubator-kie-kogito-pipelines pull request #246
Opened 2021-08-26 08:04 UTC by radtriste

# JIRA
https://issues.redhat.com/browse/PLANNER-2474

# Cherry-pick
https://github.com/kiegroup/kogito-pipelines/pull/215

# Related PRs:
* https://github.com/kiegroup/kogito-pipelines/pull/246
* https://github.com/kiegroup/optaplanner/pull/1529
* https://github.com/kiegroup/optaplanner-quickstarts/pull/165
* https://github.com/kiegroup/optaweb-employee-rostering/pull/681
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/551

2021-09-22 08:30 UTC, radtriste commented on .ci/project-dependencies.yaml
> +            target: main
This part will need to be backported to `main` branch as long as https://github.com/kiegroup/github-action-build-chain/issues/168 is not solved

2021-09-23 06:59 UTC, rsynek reviewed
I just quickly scrolled through this PR and LGTM. @Ginxo can hopefully review this in depth.

2021-09-23 07:37 UTC, radtriste commented on .ci/project-dependencies.yaml
> +            target: main
https://github.com/kiegroup/kogito-pipelines/pull/268

2021-09-23 07:45 UTC, Ginxo requested changes
please check

2021-09-23 07:45 UTC, Ginxo commented on .ci/jenkins/Jenkinsfile.buildchain
> +                            sh "build-chain-action -token=${GITHUB_TOKEN} -df='https://raw.githubusercontent.com/\${GROUP}/kogito-pipelines/main/.ci/${buildChainActionInfo.file}' -folder='bc' build $
is `https://raw.githubusercontent.com/\${GROUP}/kogito-pipelines/main` the right branch? shouldn't it be `1.11.x`?

2021-09-23 07:57 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.buildchain
> +                            sh "build-chain-action -token=${GITHUB_TOKEN} -df='https://raw.githubusercontent.com/\${GROUP}/kogito-pipelines/main/.ci/${buildChainActionInfo.file}' -folder='bc' build $
true but note that the prepare release branch will not solve that when creating a new branch ...

2021-09-23 07:59 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.buildchain
> +                            sh "build-chain-action -token=${GITHUB_TOKEN} -df='https://raw.githubusercontent.com/\${GROUP}/kogito-pipelines/main/.ci/${buildChainActionInfo.file}' -folder='bc' build $
I am just thinking. it could be a value we pass as env variable. So we don't need to hardode. wdyt ?

2021-09-23 10:42 UTC, Ginxo commented on .ci/jenkins/Jenkinsfile.buildchain
> +                            sh "build-chain-action -token=${GITHUB_TOKEN} -df='https://raw.githubusercontent.com/\${GROUP}/kogito-pipelines/main/.ci/${buildChainActionInfo.file}' -folder='bc' build $
@radtriste I agree on using env var there, we should apply the same in main branch.

2021-09-23 11:46 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.buildchain
> +                            sh "build-chain-action -token=${GITHUB_TOKEN} -df='https://raw.githubusercontent.com/\${GROUP}/kogito-pipelines/main/.ci/${buildChainActionInfo.file}' -folder='bc' build $
I will harcode that here and do a PR on `main` for the next release branches

2021-09-23 11:57 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.buildchain
> +                            sh "build-chain-action -token=${GITHUB_TOKEN} -df='https://raw.githubusercontent.com/\${GROUP}/kogito-pipelines/main/.ci/${buildChainActionInfo.file}' -folder='bc' build $
https://github.com/kiegroup/kogito-pipelines/pull/270

2021-09-24 06:38 UTC, merged