[KOGITO-2437] - Migarate namespace-cleaning job to rhba jenkins
apache/incubator-kie-kogito-pipelines pull request #37
Opened 2020-06-16 13:18 UTC by msmagnanijr

See: https://issues.redhat.com/browse/KOGITO-2437

Signed-off-by: Mauricio Magnani <mmagnani@redhat.com>

2020-06-16 13:43 UTC, Kaitou786 commented
@msmagnanijr shouldn't we also make changes in the script or in the pipeline to authenticate with openshift.?

2020-06-16 13:50 UTC, radtriste commented
yes we should

2020-06-16 13:51 UTC, radtriste commented
from my PRs to migrate jobs, I am using some credentials:
https://github.com/kiegroup/kogito-images/pull/182/files#diff-4c6c57cd8094d1a0078f1cfa0e02fcf9R38

- OPENSHIFT_API
- OPENSHIFT_CREDS

I think we should sync on that

2020-06-16 14:00 UTC, msmagnanijr commented
> from my PRs to migrate jobs, I am using some credentials:
> https://github.com/kiegroup/kogito-images/pull/182/files#diff-4c6c57cd8094d1a0078f1cfa0e02fcf9R38
> 
> * OPENSHIFT_API
> * OPENSHIFT_CREDS
> 
> I think we should sync on that

Okay! I'll take a look :)

2020-06-16 14:01 UTC, msmagnanijr commented
> @msmagnanijr shouldn't we also make changes in the script or in the pipeline to authenticate with openshift.?

yep! It was that before we had that node that was already authenticated but yes, it makes sense now to have authentication.

2020-06-22 13:06 UTC, Kaitou786 requested changes

2020-06-22 13:06 UTC, Kaitou786 commented on clean-old-namespaces-Jenkinsfile
> +    agent { label 'kogito-operator-slave && !master'}
Can we use `kogito-cloud` label over here?

2020-06-22 13:06 UTC, Kaitou786 commented
Apart from label LGTM

2020-06-22 18:06 UTC, Kaitou786 approved these changes

2020-06-22 19:30 UTC, spolti approved these changes

2020-06-23 07:39 UTC, merged