KOGITO-1031 Run BDD tests from PR
apache/incubator-kie-kogito-pipelines pull request #46
Opened 2020-07-24 23:06 UTC by Kevin-Mok

See: https://issues.redhat.com/browse/KOGITO-1031

## Summary of Changes
For this task, I mostly copied the Jenkinsfile.nightly with a couple minor differences: the promote stages are removed, and relevant `ghprb` environment variables are passed as parameters to the runtimes deploy Jenkinsfile. The changes I made from the nightly file can be found [here](https://github.com/Kevin-Mok/kogito-pipelines/compare/723febd..6907250).

## Changes to Runtimes
I had to add [new parameters](https://github.com/Kevin-Mok/kogito-runtimes/commit/105d2608f5e079744111f22bab7628781550bf56) to the runtimes deploy file to take in the new `ghprb` variables. @radtriste, you suggested using `checkoutIfExists()` with the `GIT_AUTHOR` parameter presumably, but I don't think this will work since the PR author could have an existing fork of the other repositories with an incorrect or outdated branch. As such, we only want to use the specific branch on their PR which is what the changes were done for.

Also @radtriste, did you want me to add these changes to the [KOGITO-2286 PR](https://github.com/kiegroup/kogito-runtimes/pull/570)?

## Job DSL Plugin
Setting up the GitHub Pull Request Builder requires a bit more configuring than usual while setting up the pipeline, and I came across the [Job DSL plugin](https://plugins.jenkins.io/job-dsl/) while looking at the documentation for GHPRB. It's able to turn a custom syntax into a Jenkins pipeline configuration which I think is very handy in this case given the number of options that need to be set for multiple jobs (we need one pipeline per repository to check for new PR's/comments). It saves time, and I believe it to be a good use case of having infrastructure as code. The files can be used to create new pipelines as well as update existing pipelines; the updates can then also be tracked through Git. If there are other pipelines that require some more configuration, I believe using this plugin would be quite useful to setup in those cases as well.

For this task, I created 3 DSL scripts (one for each repo) with the only differences between them being the pipeline name and GitHub URL. We can also get rid of 2 if we just manually change the values while creating the pipelines.

## Testing
I did not run a full test build of the entire pipeline since that would mostly just be testing the building portion of the nightly pipeline.  Instead, I only tested the changes I made to the nightly pipeline:
1. [Setup a pipeline](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kmok/job/KOGITO-1031/job/job-dsl/21/) using the job DSL script.
2. Triggering the pipeline by [commenting the trigger phrase](https://github.com/Kevin-Mok-Bot/jenkins-test/pull/21#issuecomment-663341547) in a PR.
3. Ensure that the [master pipeline runs](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kmok/job/KOGITO-1031/job/kogito-runtimes-test/17/console) which passes the necessary `ghprb` environment vars to the mock runtimes deploy pipeline and runs it.
4. In the [mock runtimes deploy pipeline](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kmok/job/KOGITO-1031/job/kogito-runtimes-deploy-clone-test/10/console), it clones all the repositories not associated with the PR from `kiegroup/master`; the one associated with the PR clones that author's repo and branch from the PR using the received `ghprb` variables.
5. From there, the rest of the runtimes deploy and nightly pipeline remains the same without the promotion.

## Question About Using Webhooks
I noticed in the currently running `KIE/kogito/ghprb-webhooks` pipelines, they use GitHub webhooks to trigger GHPRB. This didn't work for me as GitHub fails to send the payload to the RHBA Jenkins server as I guess it's on the VPN. I instead used the `cron` setting to poll the PR's for updates to get it to work. How does this work for the current webhook pipelines?

2020-07-27 12:46 UTC, radtriste commented on Jenkinsfile.test-pr
> +        BUILD_NAME = "${getPRRepoName()}-pr-${env.ghprbPullId}-tests"
please use same structure for those `ghrpb` variable: https://github.com/kiegroup/kogito-runtimes/blob/b0c01cee82de027650f7ee73f6a529449b954500/Jenkinsfile#L3

2020-07-27 12:46 UTC, radtriste commented on Jenkinsfile.test-pr
> +OPERATOR_PROMOTE = "kogito-operator-promote"
please remove those as not used

2020-07-27 12:46 UTC, radtriste commented on Jenkinsfile.test-pr
> +}
I think that can be deleted

2020-07-27 12:46 UTC, radtriste commented on Jenkinsfile.test-pr
> +    emailext body: "Kogito nightly build #${BUILD_NUMBER} was: ${currentBuild.currentResult}\nPlease look here: ${RUN_DISPLAY_URL}",
This one should be handled by `mailer` shared lib. See https://github.com/kiegroup/kogito-runtimes/blob/b0c01cee82de027650f7ee73f6a529449b954500/Jenkinsfile#L70

2020-07-27 12:46 UTC, radtriste commented on Jenkinsfile.test-pr
> +    }
I think those parameters can be removed as they won't be used in the PR check

2020-07-27 12:46 UTC, radtriste commented on Jenkinsfile.test-pr
> +        TEMP_TAG = "temp-${env.BUILD_NAME}"
here add a comment that this should be updated once `concurrentBuild` is enabled

2020-07-27 12:46 UTC, radtriste commented on Jenkinsfile.test-pr
> +        BRANCH_FOR_LATEST="master"
that can be removed. there is no push of latest to be done

2020-07-27 12:46 UTC, radtriste commented on Jenkinsfile.test-pr
> +                    def buildParams = getDefaultBuildParams()
I think here we should handle the case where runtimes has been changed and it impacted images build/test so that the same branch name is created there and we should checkout that one.

2020-07-27 12:46 UTC, radtriste commented on Jenkinsfile.test-pr
> +                    def buildParams = getDefaultBuildParams()
Same here, I think here we should handle the case where runtimes has been changed and it impacted operator build/test so that the same branch name is created there and we should checkout that one.

2020-07-27 12:46 UTC, radtriste commented on Jenkinsfile.test-pr
> +                    addStringParam(buildParams, "EXAMPLES_REF", "${BRANCH_NAME}")
for the examples, we should use the ones from same PR branch name if available or `kiegroup/master` if not.
in that case, there are 2 things to update:
- EXAMPLES_REF => PR branch name on `author/repo` if exist or `master`
- EXAMPLES_URI => PR author if `author/repo` exist with same branch name or `kiegroup` repo otherwise

This should be determined in this pipeline.

2020-07-27 12:46 UTC, radtriste commented on Jenkinsfile.test-pr
> +                    addStringParam(buildParams, "PR_REPO", getPRRepoName())
waiting for the runtimes pipeline to verify those ;)

2020-07-29 02:55 UTC, Kevin-Mok commented on Jenkinsfile.test-pr
> +        BUILD_NAME = "${getPRRepoName()}-pr-${env.ghprbPullId}-tests"
There are no triggers for GHPRB in a multi-branch pipeline (which is where the `CHANGE_*` variables come from), so I didn't use it. Aren't multi-branch pipelines for projects where you want to run different pipelines for different branches? But in this case, wouldn't we want GHPRB to always trigger the Jenkinsfile.test-pr from the `master` branch?

2020-07-29 03:28 UTC, Kevin-Mok commented on Jenkinsfile.test-pr
> +        BUILD_NAME = "${getPRRepoName()}-pr-${env.ghprbPullId}-tests"
Where do the `CHANGE_*` vars come from? Also, `CHANGE_BRANCH` doesn't seem to be an [existing environment variable](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/env-vars.html/).  Is it supposed to be `BRANCH_NAME`?

2020-07-29 03:29 UTC, Kevin-Mok commented on Jenkinsfile.test-pr
> +        TEMP_TAG = "temp-${env.BUILD_NAME}"
Isn't this unique enough with the repo name and PR ID? There shouldn't be more than one build at a time with the same PR, right?

2020-07-29 03:30 UTC, Kevin-Mok commented on Jenkinsfile.test-pr
> +                    addStringParam(buildParams, "PR_REPO", getPRRepoName())
I'm not sure what to do about this comment. :sweat_smile:

2020-07-29 03:38 UTC, Kevin-Mok commented
@radtriste The diff for the requested fixes can be found [here](https://github.com/Kevin-Mok/kogito-pipelines/compare/d4cb4b4..3845977). I ran the same test process as in the original comment, and everything still seems to work as intended.

### Testing Branch Parameter Helper Functions
I wrote helper functions to add in the author/branch params if the PR branch exists in the other repos. I wanted to test these functions with jenkins-spock, but I couldn't get it to work due to a combination of class errors and not being able to run the shared library functions from the Jenkinsfile during the test. [Here](https://github.com/Kevin-Mok/kogito-pipelines/tree/KOGITO-1031-spock-tests) is the branch I committed my work to if you want to check it out. I ended up manually testing the helper functions in [this build](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/custom%2Fkmok%2FKOGITO-1031%2Fjenkins-test/detail/jenkins-test/33/pipeline/48).

### Using `checkoutIfExists` in Runtimes
I ended up just using [`checkoutIfExists()` for cloning repos in runtimes](https://github.com/Kevin-Mok/kogito-runtimes/commit/d581b3f8e61140d9b2414ee952e7bbbb2a7b7a5b) to simplify the changes needed to be made in it for the PR checks.

2020-07-31 14:57 UTC, radtriste commented on Jenkinsfile.test-pr
> +        TEMP_TAG = "temp-${env.BUILD_NAME}"
oh I misread ... yeah should be enough :)

2020-07-31 14:57 UTC, radtriste commented on Jenkinsfile.test-pr
> +    parameters {
all parameters can be removed

2020-07-31 14:57 UTC, radtriste commented on Jenkinsfile.test-pr
> +        MAVEN_REPOSITORY = "http://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8081/nexus/content/repositories/kogito-runtimes-pr-artifacts/"
this is internal uri, I would put it as an env/creds in Jenkins instead

2020-07-31 14:57 UTC, radtriste commented on Jenkinsfile.test-pr
> +                    addStringParam(buildParams, "PR_TARGET_BRANCH", changeTarget)
any PR for https://github.com/Kevin-Mok/kogito-runtimes/commit/d581b3f8e61140d9b2414ee952e7bbbb2a7b7a5b ?

2020-07-31 14:57 UTC, radtriste commented on Jenkinsfile.test-pr
> +// Should be multibranch pipeline
just realized that all our PR checks are now single pipeline. do we really plan to have a multibranch pipeline.

2020-08-01 00:45 UTC, Kevin-Mok commented on Jenkinsfile.test-pr
> +                    addStringParam(buildParams, "PR_TARGET_BRANCH", changeTarget)
Did you want me to add this to the [runtimes release pipeline PR](https://github.com/kiegroup/kogito-runtimes/pull/570) or create a separate one?

2020-08-01 00:46 UTC, Kevin-Mok commented on Jenkinsfile.test-pr
> +// Should be multibranch pipeline
I didn't think so, but I wasn't sure. :sweat_smile: I was thinking that all the PR checks would be run using the Jenkinsfile.test-pr from `master`.

2020-08-01 00:55 UTC, Kevin-Mok commented on Jenkinsfile.test-pr
> +    parameters {
So, I guess both uses of the parameter will be `false` then?
1. https://github.com/Kevin-Mok/kogito-pipelines/blob/f080006e5b0abb4cf78afd54a7974ce5d8ca5c01/Jenkinsfile.test-pr#L93
2. https://github.com/Kevin-Mok/kogito-pipelines/blob/f080006e5b0abb4cf78afd54a7974ce5d8ca5c01/Jenkinsfile.test-pr#L140

2020-08-01 00:58 UTC, Kevin-Mok commented on Jenkinsfile.test-pr
> +        MAVEN_REPOSITORY = "http://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8081/nexus/content/repositories/kogito-runtimes-pr-artifacts/"
Created [the credential `PR_CHECK_MAVEN_REPOSITORY`](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/ghprb-webhooks/credentials/store/folder/domain/_/credential/PR_CHECK_MAVEN_REPOSITORY/) in `KIE/kogito/ghprb-webhooks` with the URL and used it here.

2020-08-03 08:31 UTC, radtriste commented on Jenkinsfile.test-pr
> +    parameters {
yep

2020-08-03 08:31 UTC, radtriste commented on Jenkinsfile.test-pr
> +                    addStringParam(buildParams, "PR_TARGET_BRANCH", changeTarget)
please create a separate one

2020-08-05 22:09 UTC, Kevin-Mok commented on Jenkinsfile.test-pr
> +                    addStringParam(buildParams, "PR_TARGET_BRANCH", changeTarget)
I think it would have to be done after the release pipeline PR then because it modifies the `cloneRepo` helper function which is only introduced after our PR.

2020-08-20 13:43 UTC, radtriste approved these changes

2020-08-28 00:11 UTC, Kevin-Mok commented
I can't seem to request additional reviewers on this PR. @Kaitou786, @Ginxo, @mbiarnes, could I get your reviews on this PR in addition to [the accompanying one](https://github.com/kiegroup/kogito-runtimes/pull/731)?

2020-09-02 18:26 UTC, Kevin-Mok commented
I was eventually able to get a few runtimes deploy builds to pass but will elect to use the release branches for testing in the future. However, the build now fails in [the images deploy pipeline](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/kogito-images-deploy/154/console) with this error:
```
+ python3 scripts/update-maven-artifacts.py --repo-url http://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8081/nexus/content/repositories/kogito-runtimes-pr-artifacts/
Traceback (most recent call last):
  File "scripts/update-maven-artifacts.py", line 134, in <module>
    update_artifacts(service, moduleYamlFile)
  File "scripts/update-maven-artifacts.py", line 115, in update_artifacts
    artifact['url']=getRunnerURL(service)
  File "scripts/update-maven-artifacts.py", line 78, in getRunnerURL
    finalVersion=getSnapshotVersion(service)
  File "scripts/update-maven-artifacts.py", line 66, in getSnapshotVersion
    root=getMetadataRoot(service)
  File "scripts/update-maven-artifacts.py", line 55, in getMetadataRoot
    tree = ET.parse('maven-metadata.xml')
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: mismatched tag: line 12, column 4
```

I assume this is because it cannot find the `maven-metadata.xml` file at http://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8081/nexus/content/repositories/kogito-runtimes-pr-artifacts/maven-metadata.xml.  But, the way I uploaded the artifacts from the runtimes deploy pipeline was by [uploading a zip](https://github.com/Kevin-Mok/kogito-runtimes/blob/KOGITO-1031/Jenkinsfile.deploy#L200-L205) to the `content-compressed` folder on the Nexus repository. I got this method from the [kie-jenkins-scripts](https://github.com/kiegroup/kie-jenkins-scripts/blob/56e91745ac98d4529b4414ecca37f5f3e87dedc3/job-dsls/jobs/dailyBuild_pipeline.groovy#L111-L114) and was under the impression from [this Nexus support article](https://support.sonatype.com/hc/en-us/articles/213465818-How-can-I-programmatically-upload-an-artifact-into-Nexus-2-) that: 
> The files will be unpacked and deployed individually on the server side, just as if they had been individually deployed from a client using standard deploy mechanisms.

But, this doesn't seem to be the case. Since I am using the same user credentials as in the kie-jenkins-scripts, the user should have the "Unpack" privilege, but could it be because it doesn't have create privileges in the PR artifact repository?

2020-09-21 06:30 UTC, Ginxo requested changes
Please review.
I can't tell about business here, just my technical review

2020-09-21 06:30 UTC, Ginxo commented on Jenkinsfile.pr-bdd-tests
> +void addImageBuildParams(List buildParams = [], String paramsPrefix = "", String tag, boolean isRegistryIncluded = false, boolean isFinalImage = false){
We shouldn't mix default and non-default arguments. I would recommend to short arguments to place non-default on at the beginning and default ones at the end. This is what I propose
`void addImageBuildParams(String tag, List buildParams = [], String paramsPrefix = "", boolean isRegistryIncluded = false, boolean isFinalImage = false)`

2020-09-21 06:30 UTC, Ginxo commented on Jenkinsfile.pr-bdd-tests
> +                    addStringParam(buildParams, "PR_TARGET_BRANCH", changeTarget)
This is not so important, but if you want you can replace every GString "whatever" where ${} is not used by String 'whatever'

2020-09-21 06:30 UTC, Ginxo commented on Jenkinsfile.pr-bdd-tests
> +    return prefix == null || prefix == '' ? paramId : "${prefix}_${paramId}"
this can be replaced by `return prefix ? "${prefix}_${paramId}" : paramId`

2020-09-21 06:30 UTC, Ginxo commented on JenkinsfilePrBddTests.groovy
> +            Jenkinsfile.getBinding().setVariable('env', ['ghprbGhRepository' : 'foo/bar'])
please fix indentation problems

2020-09-24 21:39 UTC, Kevin-Mok commented on Jenkinsfile.pr-bdd-tests
> +void addImageBuildParams(List buildParams = [], String paramsPrefix = "", String tag, boolean isRegistryIncluded = false, boolean isFinalImage = false){
This was copied from the nightly Jenkinsfile. I fixed it in there as well.

2020-09-24 21:40 UTC, Kevin-Mok commented on Jenkinsfile.pr-bdd-tests
> +                    addStringParam(buildParams, "PR_TARGET_BRANCH", changeTarget)
This was fixed in the master copy of the nightly Jenkinsfile, but I guess I copied an old version. Fixed.

2020-09-24 21:42 UTC, Kevin-Mok commented on JenkinsfilePrBddTests.groovy
> +            Jenkinsfile.getBinding().setVariable('env', ['ghprbGhRepository' : 'foo/bar'])
Isn't this how the [jenkins-spock examples](https://github.com/ExpediaGroup/jenkins-spock/blob/935c4f2fc0d1fbe695cc6237597fc5a0cbe5e84c/examples/whole-pipeline/src/test/groovy/JenkinsfileSpec.groovy#L16-L27) are indented?

2020-09-29 05:51 UTC, Ginxo approved these changes
LGTM

2020-09-29 07:23 UTC, Kaitou786 approved these changes

2020-09-29 08:30 UTC, radtriste commented on Jenkinsfile.pr-bdd-tests
> +void addImageBuildParams(List buildParams = [], String paramsPrefix = "", String tag, boolean isRegistryIncluded = false, boolean isFinalImage = false){
I would keep here the `buildParams` as first argument for clarity with the method name. But it does not need to have a default value.

2020-09-29 08:42 UTC, radtriste requested changes
Good job ! See my comments.

Also it would be good to put in place GH Actions or Jenkins job as you put some tests for the pipeline

2020-09-29 08:42 UTC, radtriste commented on Jenkinsfile.pr-bdd-tests
> +                    addStringParam(buildParams, 'MAVEN_ARTIFACT_REPOSITORY', env.MAVEN_REPOSITORY) // Added to be sure to get latest snapshots
Like it is done for operator, we would need to add the examples ref&uri
https://github.com/kiegroup/kogito-images/blob/master/Jenkinsfile.deploy#L45-L46

2020-09-29 08:42 UTC, radtriste commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Colud we put that one in a separate `jenkins-test` folder ?

2020-11-18 05:05 UTC, Kevin-Mok commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I put the test file in a separate folder if we wanted test files for the other pipelines, but shouldn't this `pom.xml` file remain in the base directory so we can run `mvn test` from the base directory?

2020-11-18 05:07 UTC, Kevin-Mok commented
@radtriste I redid all my changes from `master`'s Jenkinsfile.nightly and created a separate branch to compare the changes I made [here](https://github.com/Kevin-Mok/kogito-pipelines/commit/5352fb30364bd676a717e3faa59fa558f1352159#diff-fb9ad4c78657df5d4cc2ec83be59d20ccd65de9a648d64f498b73d897c22799bR1). I also went over all the review comments again to make sure they were implemented, and I copied the GitHub action file from the shared libraries to run the Spock unit tests for PR's. This seems to work as intended when I tested it [in my own repo](https://github.com/Kevin-Mok/kogito-pipelines/pull/1/checks).

I could not properly test the pipeline though due to the Docker quota problems the CI is having (see [this build](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kmok/job/KOGITO-1031-full/job/kogito-runtimes-deploy/28/console)). Perhaps you can just go over the code for now, and I will retest the pipeline once it is fixed?

2020-11-18 17:46 UTC, radtriste requested changes

2020-11-18 17:46 UTC, radtriste commented on Jenkinsfile.pr-bdd-tests
> +        BRANCH_FOR_LATEST='master'
not used here

2020-11-18 17:46 UTC, radtriste commented on Jenkinsfile.pr-bdd-tests
> +                    addAuthorBranchParamsIfExist(buildParams, getPRRepoName())
shouldn't we do the same in case we have same branch on optaplanner/examples/images/operator to take change into account ?

2020-11-18 17:46 UTC, radtriste commented on Jenkinsfile.pr-bdd-tests
> +void addAuthorBranchParamsIfExist(List params, String repo) {
thinking what would happen if the branch is not against `master` and the `changeAuthor/changeBranch` does not exist
We should also check if `getPRRepoName()/changeTarget` exist to be set for deploy job calls if exist

2020-11-18 17:47 UTC, radtriste commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I guess the GHAction should be executed into the jenkins-test folder. would that be possible ?

2020-11-18 23:48 UTC, Kevin-Mok commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I moved it into the jenkins-test folder, modified the paths and it [seems to work still](https://github.com/Kevin-Mok/kogito-pipelines/pull/2/checks).

2020-11-18 23:56 UTC, Kevin-Mok commented on Jenkinsfile.pr-bdd-tests
> +void addAuthorBranchParamsIfExist(List params, String repo) {
In the case that the `changeAuthor/changeBranch` doesn't exist (so not in the runtimes stage) and the target branch isn't `master` (so a release branch), then we want the resulting pipeline to build the release branch from `kiegroup`. I add [an `else if` branch](https://github.com/Kevin-Mok/kogito-pipelines/blob/9c60c26ef4c4aa44a4eba821aaf9d0abaafb4683/Jenkinsfile.pr-bdd-tests#L210-L212) for this case and added [a unit test](https://github.com/Kevin-Mok/kogito-pipelines/blob/9c60c26ef4c4aa44a4eba821aaf9d0abaafb4683/jenkins-tests/JenkinsfilePrBddTests.groovy#L41-L49) for it.

2020-11-19 07:45 UTC, radtriste commented on Jenkinsfile.pr-bdd-tests
> +                    addStringParam(buildParams, 'PR_TARGET_BRANCH', changeTarget)
this should be added also for other deploy pipelines

2020-11-20 07:16 UTC, radtriste commented on Jenkinsfile.pr-bdd-tests
> +String getPRRepoName() {
Could we leverage https://github.com/kiegroup/jenkins-pipeline-shared-libraries/blob/de9ebbdd91cab38a0337c4b5e2dac8a23f8ba486/vars/util.groovy#L83 instead ?

2020-11-23 15:13 UTC, Kevin-Mok commented on Jenkinsfile.pr-bdd-tests
> +                    addStringParam(buildParams, 'PR_TARGET_BRANCH', changeTarget)
I think this only needs to be added to runtimes (possibly OptaPlanner as well?) because it's checking out multiple repositories. In the other jobs where it's only checking out a single repository, `addAuthorBranchParamsIfExist()` will pass in the PR branch if it exists or the release branch if the target branch is not `master`. Otherwise, the default parameter value of `master` works fine.

2020-11-23 15:13 UTC, Kevin-Mok commented on Jenkinsfile.pr-bdd-tests
> +String getPRRepoName() {
That function takes in a URL. I could use `util.getProjectGroupName(env.ghprbGhRepository)[1]`, but this seems simpler. :stuck_out_tongue:

2020-11-23 15:14 UTC, Kevin-Mok commented
@radtriste I started testing the pipeline since it seems I'm not running into the Docker quota issue any more, but I ran into [this banned repository issue](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/optaplanner-deploy/118/execution/node/172/log/). Apparently it has to do with [the repository not being HTTPS](https://stackoverflow.com/questions/62299435/current-maven-session-contains-banned-plugin-repository-urls-please-double-chec). Do you know how I can get around this?

2020-11-23 15:47 UTC, radtriste commented on Jenkinsfile.pr-bdd-tests
> +                    addStringParam(buildParams, 'PR_TARGET_BRANCH', changeTarget)
ah so this parameter is there because we have both runtimes & apps in kogito-runtimes ?

2020-11-23 15:49 UTC, Kevin-Mok commented on Jenkinsfile.pr-bdd-tests
> +                    addStringParam(buildParams, 'PR_TARGET_BRANCH', changeTarget)
Yep. So, I'm using `checkoutIfExists` so that it can fall back to the PR target branch for the repository that the PR is not in.

2021-01-15 16:25 UTC, radtriste commented on pr-bdd-tests-job-dsl.groovy
> +pipelineJob('KIE/kogito/ghprb-webhooks/kogito-runtimes-bdd') {
could be put in a `jenkins/dsl` folder instead

2021-01-15 16:55 UTC, Kevin-Mok commented on pr-bdd-tests-job-dsl.groovy
> +pipelineJob('KIE/kogito/ghprb-webhooks/kogito-runtimes-bdd') {
This is for the actual pipeline though. Maybe the DSL job can be put into `KIE/kogito/ghprb-webhooks/dsl`, but [the `KIE/kogito/ghprb-webhooks` folder](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/ghprb-webhooks/) (where all the other PR check pipelines are) seems fine to put this and the other BDD ones (runtimes, apps, examples) as well?

2021-01-15 17:04 UTC, radtriste commented on pr-bdd-tests-job-dsl.groovy
> +pipelineJob('KIE/kogito/ghprb-webhooks/kogito-runtimes-bdd') {
oh I meant the groovy file `pr-bdd-tests-job-dsl.groovy` should be in `jenkins/dsl/pr-bdd-tests-job-dsl.groovy` path not at the root

2021-01-15 17:29 UTC, radtriste approved these changes

2021-01-19 07:39 UTC, merged