KOGITO-7921: upgrading kogito version in quarkus platform
apache/incubator-kie-kogito-pipelines pull request #617
Opened 2022-09-21 09:12 UTC by mbiarnes

JIRA: [KOGITO-7921](https://issues.redhat.com/browse/KOGITO-7921)

These changes basically do the same s using before manually https://github.com/kiegroup/kogito-pipelines/blob/main/tools/update-quarkus-platform.sh

The user has the option to do a 

- `stage` followed by a `finalize`  or 
- in case he wants to `finalize` directly he has the option `finalize`

All this was tested against my personal kogito-pipelines and quarkus-platform and it worked.
The PR opened in the `stage` had the changes in mvn-settings.xml whereas this change was removed again when it came to `finalize`.
In case the user wants to `finalize' directly (corner cases) this change of mvn-settings.xml is not needed.

2022-09-23 08:44 UTC, radtriste requested changes

2022-09-23 08:44 UTC, radtriste commented on tools/update-kogito-quarkus-platform.sh
> +#!/usr/bin/env bash
Why creating a new shell script ?
the existing one could be reused ;)

2022-09-23 08:44 UTC, radtriste commented on .ci/jenkins/dsl/jobs.groovy
> +void setupUpdateQuarkusPlatform() {
Please remove Kogito from the naming of the jenkinsfile and the job

2022-09-23 08:44 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.kogito.update-quarkus-platform
> +    }
Please set the author as a parameter of the method

2022-09-23 08:44 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.kogito.update-quarkus-platform
> +                        githubscm.createBranch(localBranch)
This will not work. You are checking out quarkusio author
you will need first to fork the repository into `kiegroup` and then create PR to `quarkusio` author.
Example can be found here: 
- Fork repo: https://github.com/kiegroup/kogito-runtimes/blob/main/.ci/jenkins/Jenkinsfile.deploy#L216
- PR creation to another GH author: https://github.com/kiegroup/kogito-runtimes/blob/main/.ci/jenkins/Jenkinsfile.deploy#L227

2022-09-23 08:44 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.kogito.update-quarkus-platform
> +        }
I am not sure it is a good idea to keep the job opened for days for that ...
we could have the `stage` / `finalize` as a parameter of the job and decide what to do in the script using the `when` condition on stages https://www.jenkins.io/doc/book/pipeline/syntax/#when

2022-09-23 09:49 UTC, mbiarnes commented on tools/update-kogito-quarkus-platform.sh
> +#!/usr/bin/env bash
I thought if someone want to use the "old" script locally he can do it. This script corresponding to a Jenkins job wouldn't work locally.

2022-09-23 09:55 UTC, mbiarnes commented on .ci/jenkins/dsl/jobs.groovy
> +void setupUpdateQuarkusPlatform() {
OK - will do it

2022-09-23 10:05 UTC, mbiarnes commented on .ci/jenkins/Jenkinsfile.kogito.update-quarkus-platform
> +    }
OK

2022-09-23 10:49 UTC, mbiarnes commented on tools/update-kogito-quarkus-platform.sh
> +#!/usr/bin/env bash
in case someones who has not access to the VPN wants to execute the existing script

2022-09-23 11:09 UTC, radtriste commented on tools/update-kogito-quarkus-platform.sh
> +#!/usr/bin/env bash
The script should be runnable from everywhere. it is not Jenkins dependent.
You can improve/modify the existing script with an option to by pass all the git commands for example. That way, the user can still use it on its machine and we can also execute it on Jenkins, providing the option disabling git functionalities into the script.
Having 2 scripts is a lot of maintenance honestly ...

2022-09-28 10:55 UTC, mbiarnes commented
@radtriste all changes implemented

2022-10-03 11:27 UTC, mbiarnes commented
@radtriste changes added - tested again.
On Jenkins and also locally. Both work.

2022-10-03 12:45 UTC, radtriste requested changes
Please also check the indentation

2022-10-03 12:45 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.update-quarkus-platform
> +AGENT_LABEL="kie-rhel7 && kie-mem8g && !master"
```suggestion
AGENT_LABEL="kie-rhel7 && kie-mem8g && !built-in"
```
:)

2022-10-03 12:45 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.update-quarkus-platform
> +MVN_TOOL="kie-maven-3.8.1"
```suggestion
MVN_TOOL="kie-maven-3.8.6"
```

2022-10-03 12:45 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.update-quarkus-platform
> +GIT_AUTOR='kie-ci'
rename to `FORK_GIT_AUTHOR`

2022-10-03 12:45 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.update-quarkus-platform
> +baseBranch='main'
please distinguish between `quarkusBaseBranch` and `pipelinesBaseBranch`. The latter one should be set as env of the job

2022-10-03 12:45 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.update-quarkus-platform
> +                    String commitId = ""
is unused

2022-10-03 12:45 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.update-quarkus-platform
> +                    String mergeName = ""
You don't need to define them here. Those are local and should be initialized only when you need it, aka https://github.com/kiegroup/kogito-pipelines/pull/617/files#diff-022a0f158b2d1b0eebbccfe37f033cc9acd58e9b17e2a5cd45a48aa3c889c637R88-R89

2022-10-03 12:45 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.update-quarkus-platform
> +                    String commitMsg = "bump up ${PROJECT} to ${VERSION}"
Why defining here if you use it only once ?

2022-10-03 12:45 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.update-quarkus-platform
> +                    String localBranch = "bump-${PROJECT}-${VERSION}"
Please use methods to retrieve those values, so you can reuse and avoid mistakes in maintenance.

2022-10-03 12:45 UTC, radtriste commented on .ci/jenkins/dsl/jobs.groovy
> +            JENKINS_EMAIL_CREDS_ID: "${JENKINS_EMAIL_CREDS_ID}",
add the `BUILD_BRANCH_NAME` so i can be used into the pipeline as the `pipelinesBaseBranch`

2022-10-03 12:45 UTC, radtriste commented on tools/update-quarkus-platform.sh
> +RUN_ON_JENKINS=false
Would be better to not be specific to Jenkins. This could be called: `IGNORE_GIT` or `DISABLE_GIT` instead

2022-10-05 07:59 UTC, mbiarnes commented
@radtriste LGTM - wdyt?

2022-10-14 11:46 UTC, radtriste approved these changes

2022-10-14 11:46 UTC, merged