[KOGITO-3510] Set creds as params
apache/incubator-kie-kogito-pipelines pull request #68
Opened 2020-10-02 16:07 UTC by radtriste

https://issues.redhat.com/browse/KOGITO-3510

2020-10-08 10:26 UTC, sutaakar reviewed
Looks good to me

2020-10-08 14:45 UTC, Kevin-Mok commented on Jenkinsfile.release
> +        GITHUB_TOKEN_CREDS_ID='radtriste-gh-token' // secret text creds
So, are your credentials used throughout the entire release pipeline? Don't we need KIE credentials at some point?

2020-10-08 15:03 UTC, Kevin-Mok requested changes
Seems like some lines need to be reverted from testing back to default, but it looks good otherwise. Great addition. :+1:

2020-10-08 15:03 UTC, Kevin-Mok commented on Jenkinsfile.release
> +        IMAGE_NAMESPACE = 'tradisso'
Should these be reverted as well?

2020-10-08 15:03 UTC, Kevin-Mok commented on Jenkinsfile.release
> +                    addStringParam(buildParams, 'MAVEN_ARTIFACT_REPOSITORY', env.STAGING_REPOSITORY) // Get artifacts from staging repository
Should this be re-commented?

2020-10-08 15:04 UTC, radtriste commented
@Kevin-Mok yeah I am still in draft mode in that one. I will just need to remove this commit: https://github.com/kiegroup/kogito-pipelines/pull/68/commits/95de24f2608edfb38687d8caa9d5aa31d991a6f3 ;)

2020-10-08 15:31 UTC, Kevin-Mok reviewed
Minor stylistic changes for README.

2020-10-08 15:31 UTC, Kevin-Mok commented on README.md
> +* [[kogito-images-deploy](https://github.com/kiegroup/kogito-images/blob/master/Jenkinsfile.deploy)
```suggestion
* [kogito-images-deploy](https://github.com/kiegroup/kogito-images/blob/master/Jenkinsfile.deploy)
```

2020-10-08 15:31 UTC, Kevin-Mok commented on README.md
> +* **IMAGE_NAMESPACE** (and `IMAGE_REGISTRY_CREDENTIALS`, see [Setup Jenkins creds](#setup-jenkins-creds))
```suggestion
* `GIT_AUTHOR` (and `GIT_AUTHOR_CREDS_ID`, see [Setup Jenkins creds](#setup-jenkins-creds))
* `BOT_AUTHOR` (and `BOT_AUTHOR_CREDS_ID`, see [Setup Jenkins creds](#setup-jenkins-creds))
* `IMAGE_NAMESPACE` (and `IMAGE_REGISTRY_CREDENTIALS`, see [Setup Jenkins creds](#setup-jenkins-creds))
```
I think monospace for variables is more standard?

2020-10-08 15:31 UTC, Kevin-Mok commented on README.md
> +  Email for notifications. You can set your email for example
```suggestion
* `GIT_AUTHOR_CREDS_ID` (username/password credential)  
  * Username / [GitHub token](https://github.com/settings/tokens) which has rights on `GIT_AUTHOR`
* `BOT_AUTHOR_CREDS_ID` (username/password credential)  
  * Username / [GitHub token](https://github.com/settings/tokens) which has rights on `BOT_AUTHOR`
* `GITHUB_TOKEN_CREDS_ID` (secret text credential)  
  * [GitHub token](https://github.com/settings/tokens) for Github CLI
* `IMAGE_REGISTRY_CREDENTIALS` (username/password credential)  
  * Credential to push image to the container registry (should have rights to `IMAGE_NAMESPACE`)
* `KOGITO_CI_EMAIL_TO` (secret text credential)  
  * Email for notifications. You can set your email for example
```
Same here.

2020-10-09 08:00 UTC, radtriste commented
waiting for dependent PRs to merge

2020-10-09 12:02 UTC, sutaakar approved these changes

2020-10-09 16:12 UTC, Kevin-Mok approved these changes

2020-10-12 11:32 UTC, merged