KOGITO-6259: added job for toggle triggers
apache/incubator-kie-kogito-pipelines pull request #686
Opened 2022-11-09 12:47 UTC by mbiarnes

[KOGITO-6259](https://issues.redhat.com/browse/KOGITO-6259)

2022-11-09 14:38 UTC, mbiarnes commented
@radtriste test are missing

2022-11-10 14:44 UTC, radtriste requested changes

2022-11-10 14:44 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +prBranch = "toggle-triggers-${DISABLE_TRIGGERS}"
I guess we would need a bit more random just in case an "older" branch has not been deleted.
You could use something like https://github.com/kiegroup/drools/blob/main/.ci/jenkins/Jenkinsfile.deploy#L38

2022-11-10 14:44 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +		            branchCreated = getOrCreateGitBranch(prBranch, 'kie-ci')
I wouldn't use an older branch. I would start from a totally new branch because the configuraiton format could have changed a bit in-between

2022-11-10 14:44 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +String getToggleTriggers() {
boolean ?

2022-11-10 14:44 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +		            branchCreated = getOrCreateGitBranch(prBranch, 'kie-ci')
please check the indentation

2022-11-10 14:44 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                        checkoutRepo(kogitoPipelinesRepo, 'kiegroup', getBuildBranch())
`kiegroup` should be configurable via env var. See other job with `GIT_AUTHOR` env

2022-11-10 14:44 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                        checkoutRepo(kogitoPipelinesRepo, 'kiegroup', getBuildBranch())
`checkoutRepo` should also use credentials when doing the checkout
see `GIT_AUTHOR_CREDENTIALS_ID` in other repositories

2022-11-10 14:44 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                        String commitMsg = "[" + getBuildBranch() + "] trigger was toggled to disable: ${DISABLE_TRIGGERS}"
```suggestion
                        String commitMsg = "[${getBuildBranch()}"] Triggers ${DISABLE_TRIGGERS ? 'disabled' : 'enabled'}"
```

2022-11-10 14:44 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                                sendNotification("PR was created with toggle-triggers to ${DISABLE_TRIGGERS}.\nHere is the PR link: ${prLink}")
```suggestion
                                sendNotification("PR to  ${DISABLE_TRIGGERS ? 'disable' : 'enable'} triggers has been created .\nHere is the PR link: ${prLink}")
```

2022-11-10 14:44 UTC, radtriste commented on .ci/jenkins/dsl/jobs.groovy
> +            stringParam('BRANCH', '', 'On which branch the triggers should be toggled.')
please use same naming convention as other jobs: `BUILD_BRANCH_NAME`

2022-11-10 14:44 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +             subject: "[${getBuildBranch()}] toggle triggers",
```suggestion
             subject: "[${getBuildBranch()}] Kogito",
```

2022-11-11 10:54 UTC, mbiarnes commented
@radtriste all changes done

2022-11-15 10:30 UTC, radtriste requested changes

2022-11-15 10:30 UTC, radtriste commented on .ci/jenkins/dsl/jobs.groovy
> -// PRs
Why was that removed ?

2022-11-15 10:30 UTC, radtriste commented on .ci/jenkins/dsl/jobs.groovy
> +            JENKINS_EMAIL_CREDS_ID: "${JENKINS_EMAIL_CREDS_ID}",
indentation ?

2022-11-15 10:30 UTC, radtriste commented on .ci/jenkins/dsl/jobs.groovy
> +    def jobParams = KogitoJobUtils.getBasicJobParams(this, 'toggle-triggers', Folder.TOOLS, "${JENKINSFILE_PATH}/Jenkinsfile.toggle-triggers", "Toggle triggers")
```suggestion
    def jobParams = KogitoJobUtils.getBasicJobParams(this, 'toggle-triggers', Folder.TOOLS, "${JENKINSFILE_PATH}/Jenkinsfile.toggle-triggers", "Toggle DSL triggers")
```

2022-11-15 10:30 UTC, radtriste commented on .ci/jenkins/dsl/jobs.groovy
> +            stringParam('BUILD_BRANCH_NAME', '', 'On which branch the triggers should be toggled.')
As we will execute from a specific branch folder in Jenkins, I think this could be moved to environment instead of parameters

2022-11-15 10:30 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +prBranch = "toggle-triggers"
prBranchPrefix ?

2022-11-15 10:30 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +			steps{
Please check the indentation of this file.

2022-11-15 10:30 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +		            branchCreated = getOrCreateGitBranch("${prBranch}-${PR_BRANCH_HASH}", GIT_AUTHOR)
I would say we could directly create the branch. We don't need the `getOrCreateGitBranch`

2022-11-15 10:30 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                            if ( "${branchCreated}" ) {
that could be removed as the branch should be unique. So it will be always created

2022-11-15 14:46 UTC, mbiarnes commented on .ci/jenkins/dsl/jobs.groovy
> -// PRs
error - will fix this

2022-11-16 10:09 UTC, mbiarnes commented on .ci/jenkins/dsl/jobs.groovy
> -// PRs
fixed

2022-11-16 11:43 UTC, radtriste reviewed
Minor changes

2022-11-16 11:43 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +AGENT_LABEL="kie-rhel7 && kie-mem8g && !built-in"
Do we really need a mem8g for a simple yaml update ? :)
```suggestion
AGENT_LABEL="kie-rhel7 && !built-in"
```

2022-11-16 11:43 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                        githubscm.createBranch("${prBranchPrefix}-${PR_BRANCH_HASH}")
Please use a getter to get the branch to create
Something like:

```groovy
String getPRBranch() {
    return "${prBranchPrefix}-${PR_BRANCH_HASH}"
}
```

2022-11-16 11:43 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +        stage('Raise pullrequest'){
```suggestion
        stage('Create pullrequest'){
```

2022-11-16 11:43 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                        String commitMsg = "[${getBuildBranch()}] Triggers ${DISABLE_TRIGGERS ? 'disabled' : 'enabled'}"
```suggestion
                        String commitMsg = "[${getBuildBranch()}] DSL triggers ${DISABLE_TRIGGERS ? 'disabled' : 'enabled'}"
```

2022-11-16 11:43 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                        String prLink = null
```suggestion
```

2022-11-16 11:43 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                            prLink = githubscm.createPR(commitMsg, prBody, getBuildBranch())
```suggestion
                            String prLink = githubscm.createPR(commitMsg, prBody, getBuildBranch())
```

2022-11-16 11:43 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                            githubscm.commitChanges(commitMsg, { sh "git add --all" })
`sh "git add --all"` is the default closure, so no need to send it as arg

```suggestion
                            githubscm.commitChanges(commitMsg)
```

2022-11-16 14:22 UTC, mbiarnes commented
@radtriste minor changes done

2022-11-25 14:29 UTC, radtriste reviewed
Minor comments

2022-11-25 14:29 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                sh 'printenv'
```suggestion
                    sh 'printenv'
```

2022-11-25 14:29 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                        sh "git checkout ${prBranchPrefix}-${PR_BRANCH_HASH}"
why do you checkout again ?

2022-11-25 14:29 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                        def prBody = "Generated by Kogito pipelines"
```suggestion
                        def prBody = "Generated by ${BUILD_URL}"
```

2022-11-25 14:29 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                        sh "git checkout ${getPRBranch()}"
why do you checkout again ? :)

2022-11-25 14:29 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +		}
```suggestion
		    }
		}
            }
	}
```

2022-12-05 12:25 UTC, mbiarnes commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                        sh "git checkout ${prBranchPrefix}-${PR_BRANCH_HASH}"
to be sure that I am on the right branch -

2022-12-05 12:39 UTC, mbiarnes commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                        sh "git checkout ${getPRBranch()}"
only to ensure that I am on the right branch

2022-12-05 14:39 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                        sh "git checkout ${prBranchPrefix}-${PR_BRANCH_HASH}"
but you are already. not sure it is needed to checkout again

2022-12-08 12:27 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +AGENT_LABEL="kie-rhel7 && !built-in"
```suggestion
AGENT_LABEL="kie-rhel8 && !built-in"
```

2022-12-08 12:27 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +prBranchPrefix = "toggle-triggers"
used only once in code, you could directly use the string in the `getPRBranch` method

2022-12-08 12:27 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                        sh "git checkout ${getPRBranch()}"
but you are checking out twice in the last 3 lines and anyway the `githubscm.createBranch` , on line 52, has already put you on the correct branch, so you don't need to checkout again

2022-12-08 12:27 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +}
```suggestion
void checkoutRepo(String repo, String gitAuthor, String branch, String gitAuthorCredsId) {
    checkout(githubscm.resolveRepository(repo, gitAuthor, branch, false, gitAuthorCredsId))
    // need to manually checkout branch since on a detached branch after checkout command
    sh "git checkout ${branch}"
}
```

2022-12-15 09:17 UTC, mbiarnes commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                        sh "git checkout ${getPRBranch()}"
OK  - removed the checkouts

2022-12-15 09:23 UTC, mbiarnes commented
@radtriste all changes done

2022-12-22 10:00 UTC, radtriste requested changes

2022-12-22 10:00 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                        if (githubscm.isThereAnyChanges()) {
I would not create a PR but push directly to the repository.
We want quick action there, no need for review, it is just a boolean change :)

2022-12-22 10:00 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +        }
can we send a notification if `success` ?
that way we are aware of the change on Zulip

2023-01-10 16:09 UTC, mbiarnes commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +        }
isn't this already done with `sendNotification` https://github.com/kiegroup/kogito-pipelines/pull/686/files#diff-fe0bdb6d98b7bf563cdd5433baa51b61a80c1a8e752c8604220ee88dce4929aeR82

2023-01-10 16:12 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +        }
indeed

2023-01-11 15:04 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.toggle-triggers
> +                            mergeAndPush(prLink, getBuildBranch())
before merge and push, you need to checkout back the `getBuildBranch()`

2023-01-30 14:24 UTC, radtriste approved these changes

2023-01-30 15:04 UTC, mareknovotny approved these changes

2023-01-30 15:04 UTC, merged