[KOGITO-8115] added Nexus repository for nightly deploy job
apache/incubator-kie-kogito-pipelines pull request #696
Opened 2022-11-15 09:37 UTC by mbiarnes

2022-11-16 16:28 UTC, radtriste requested changes

2022-11-16 16:28 UTC, radtriste commented on dsl/config/branch.yaml
> +    creds_id: kie-ci1-upload
I think you should use the already existing `artifacts_repository` and add a `artifacts_repository_credentials_id`
```suggestion
  artifacts_repository: https://repository.jboss.org/nexus/content/repositories/snapshots/
  artifacts_repository_credentials_id: kie-ci1-upload
```

2022-11-16 16:29 UTC, radtriste commented on dsl/config/branch.yaml
> +    creds_id: kie-ci1-upload
forget about this

2022-11-16 16:30 UTC, radtriste commented on dsl/config/branch.yaml
> +  local_zipped_artifacts_repository:
```suggestion
  artifacts_upload_repository:
```

2022-11-17 14:12 UTC, mbiarnes commented
@radtriste comments resolved

2022-11-24 14:21 UTC, radtriste approved these changes

2022-11-24 14:47 UTC, merged