[KOGITO-2293] - Setup job to cleanup old images nightlies
apache/incubator-kie-kogito-pipelines pull request #7
Opened 2020-05-26 09:09 UTC by Kaitou786

See: https://issues.redhat.com/browse/KOGITO-2293

Signed-off-by: TARUN KHANDELWAL <tarkhand@redhat.com>

2020-05-26 10:27 UTC, radtriste requested changes

2020-05-26 10:27 UTC, radtriste commented on tools/clean-nightly-tags.py
> +    print("QUAY_ACCESS_TOKEN enviornment variable is not set. Please, set and export on shell and run the script again")
```suggestion
    print("QUAY_ACCESS_TOKEN environment variable is not set. Please set it before running the script.")
```

2020-05-26 10:27 UTC, radtriste commented on tools/clean-nightly-tags.py
> +    exit('Script exciting....')
```suggestion
    exit('Script exiting....')
```

2020-05-26 10:27 UTC, radtriste commented on tools/clean-nightly-tags.py
> +# QUAY_ACCESS_TOKEN is needed to set as enviornment variable before executing script
```suggestion
# QUAY_ACCESS_TOKEN is needed to set as environment variable before executing script
```

2020-05-26 10:27 UTC, radtriste commented on tools/clean-nightly-tags.py
> +# The access token is used for authentication against the quay apis.
```suggestion
# The access token is used for authentication against the quay api.
```

2020-05-26 10:27 UTC, radtriste commented on tools/clean-nightly-tags.py
> +        delete_image_tags(image,args.max_tags)
Could we have a method `get_and_delete_old_tags` that will call `get_image_tags` and then call `delete_image_tags` with the exact tags to delete ?

2020-05-26 10:27 UTC, radtriste commented on tools/clean-nightly-tags.py
> +            requests.delete('https://{0}/api/v1/repository/{1}/{2}/tag/{3}'.format(REGISTRY,NAMESPACE,image,tags[-1]) , headers={'content-type': 'application/json', 'Authorization': 'Bearer ' + QUAY_
Can't we just loop on tags ?

2020-05-26 10:32 UTC, Kaitou786 commented on tools/clean-nightly-tags.py
> +        delete_image_tags(image,args.max_tags)
So do you mean passing the tags with the image in `delete_image_tags` as a parameter?

2020-05-26 10:34 UTC, Kaitou786 commented on tools/clean-nightly-tags.py
> +            requests.delete('https://{0}/api/v1/repository/{1}/{2}/tag/{3}'.format(REGISTRY,NAMESPACE,image,tags[-1]) , headers={'content-type': 'application/json', 'Authorization': 'Bearer ' + QUAY_
I think this better, we are just ensuring here that available tags for the image are not greater than max_tags to keep

2020-05-26 10:35 UTC, radtriste commented on tools/clean-nightly-tags.py
> +        delete_image_tags(image,args.max_tags)
yes. we determine beforehand which tags to delete and then we make the call

2020-05-26 10:36 UTC, radtriste commented on tools/clean-nightly-tags.py
> +            requests.delete('https://{0}/api/v1/repository/{1}/{2}/tag/{3}'.format(REGISTRY,NAMESPACE,image,tags[-1]) , headers={'content-type': 'application/json', 'Authorization': 'Bearer ' + QUAY_
that you can do the first time.
I don't get why you need to call back each time to get all tags whereas you already have them

2020-05-26 10:38 UTC, Kaitou786 commented on tools/clean-nightly-tags.py
> +            requests.delete('https://{0}/api/v1/repository/{1}/{2}/tag/{3}'.format(REGISTRY,NAMESPACE,image,tags[-1]) , headers={'content-type': 'application/json', 'Authorization': 'Bearer ' + QUAY_
Just to ensure that are also deleted on quay, but okay, if we assume that they are going to be deleted than yes I can just pass the tags and not get the tags again and again.

2020-05-26 12:43 UTC, spolti requested changes

2020-05-26 12:43 UTC, spolti commented on tools/clean-nightly-tags.py
> +    if len(all_tags) > max_tags:
this will delete any tag depending on the list order quay returns, we need to delete the oldest images and keep only 10.
I think the content returned by quay , besides the tag also contains a field that tells you how old are the tag.

2020-05-26 12:45 UTC, Kaitou786 commented on tools/clean-nightly-tags.py
> +    if len(all_tags) > max_tags:
Quay returns the list according to the last modification on tag. So the last values will always be the oldest

2020-05-26 14:40 UTC, radtriste commented on tools/clean-nightly-tags.py
> +    if len(all_tags) > max_tags:
we could, for the safe's side, order them by date somewhere.
If tomorrow Quay changes its API behavior, then we could have some problems ;)

2020-05-26 14:40 UTC, radtriste commented on tools/clean-nightly-tags.py
> +        tags.append(image_metadata['tags'][i]['name'])
we should get also the last updated date.
Also, we should not count `latest` in here

2020-05-26 15:01 UTC, Kaitou786 commented on tools/clean-nightly-tags.py
> +        tags.append(image_metadata['tags'][i]['name'])
Okay I'll create a struct with their date as well,
So apart from `latest` tag we need to save 10 more.

2020-05-27 12:58 UTC, spolti commented on tools/clean-nightly-tags.py
> +    if len(all_tags) > max_tags:
there is a last modified fied we could use:
`"tags": {"nightly-2020-05-25": {"image_id": "8d034a7aa8c35941a36762e5fb7b7e80b60c2a121c61219d81dd560e1298d8a9", "last_modified": "Mon, 25 May 2020 10:54:12 -0000", "name": "nightly-2020-05-25", "manifest_digest": "sha256:9a80faddd6a391f8fbf105bd4f6abecc52a6d8bf296c98e79876156c3e024498", "size": 105741819}`

2020-05-27 13:28 UTC, Kaitou786 commented on tools/clean-nightly-tags.py
> +    if len(all_tags) > max_tags:
Yeah I used that field only for the timestamp. Can you check the code?

2020-05-27 13:50 UTC, spolti approved these changes
sounds better.
thanks

2020-05-27 15:29 UTC, msmagnanijr approved these changes

2020-05-27 18:29 UTC, radtriste commented on tools/clean-nightly-tags.py
> +        tags[image_metadata['tags'][i]['name']] = parse(image_metadata['tags'][i]['last_modified'])
why not using a struct with `tagName` and `lastUpdate` fields, construct a list of those structs and then use the `sort()` method to order like we want ?
I think the code would be also more readable than just a map

2020-05-27 18:38 UTC, Kaitou786 commented on tools/clean-nightly-tags.py
> +        tags[image_metadata['tags'][i]['name']] = parse(image_metadata['tags'][i]['last_modified'])
Personally I don't think that any structure would be better over here than a dictionary with format `tag`: `last_modified`. I did try to use sort function on the value of this dictionary and later also on the dates list (with all the parsed dates) but they didn't result in correct/expected order. The `<` `>` operator was working fine on these values so I used min function which uses `<` to find the minimum value.

2020-05-28 10:38 UTC, radtriste requested changes

2020-05-28 10:38 UTC, radtriste commented on tools/clean-nightly-tags.py
> +    for i in range(len(all_tags)):
Please use `filter` method on list: https://www.programiz.com/python-programming/methods/built-in/filter
So it could be later extended if needed

2020-05-28 10:38 UTC, radtriste commented on tools/clean-nightly-tags.py
> +    num_delete_tags = len(all_tags) - max_tags #Get the number of tags that needs to be deleted
you could use `all_tags[:len(all_tags) - max_tags]` to have the subset

2020-05-28 10:38 UTC, radtriste commented on tools/clean-nightly-tags.py
> +    delete_image_tags(image,delete_tags)
please send the whole list of struct, then the `delete_image_tags` decide which information is useful

2020-05-28 13:03 UTC, radtriste requested changes

2020-05-28 13:03 UTC, radtriste commented on tools/clean-nightly-tags.py
> +    if all_tags['tagName'] == 'latest':
can't we just return `!all_tags['tagName'] == 'latest'` ?

2020-05-28 13:03 UTC, radtriste commented on tools/clean-nightly-tags.py
> +def filter_latest_tag(all_tags):
you are filtering on one tag here

2020-05-28 13:03 UTC, radtriste commented on tools/clean-nightly-tags.py
> +    QUAY_TOKEN = os.environ['QUAY_ACCESS_TOKEN']
you are checking for `QUAY_ACCESS_TOKEN` but use `QUAY_TOKEN` when making http request ...

2020-05-28 13:03 UTC, radtriste commented on tools/clean-nightly-tags.py
> +    all_tags = list(filter(filter_latest_tag,all_tags))
can't we just do `list(filter(lambda tag: tag["tagName"]!="latest", all_tags))` ?

2020-05-28 14:27 UTC, Kaitou786 commented
I'll make the changes and test the code, once quay.io is live

2020-05-29 07:04 UTC, radtriste requested changes

2020-05-29 07:04 UTC, radtriste commented on tools/clean-nightly-tags.py
> +    all_tags = list(filter(lambda tag: tag["tagName"]!="latest" ,all_tags))   #Filter out the entry with latest as tagName from the struct list
```suggestion
    all_tags = list(filter(lambda tag: tag["tagName"]!="latest", all_tags))   #Filter out the entry with latest as tagName from the struct list
```

2020-05-29 07:24 UTC, radtriste commented on tools/clean-nightly-tags.py
> +# Script responsible for removing extra tags
```suggestion
# Script responsible for removing extra tags of nightly images
```

2020-05-29 18:31 UTC, radtriste approved these changes
lgtm

2020-05-29 19:58 UTC, spolti commented
@Kaitou786 this PR the changes are good, but, shouldn't  the Nightly job be updated as well to call this script?

2020-05-31 12:00 UTC, Kaitou786 commented
@spolti I was thinking, we can have a periodic Jenkins job which runs this script every morning or after the nightly is complete and delete the images. But it can also be the last step in the nightly pipeline after the images have been published. We need to decide which approach we are going to follow. @radtriste @msmagnanijr  please share your thoughts on this.

2020-06-01 14:20 UTC, spolti commented
It can be a something on the nightly pipeline, after push the new images, delete the oldest ones.
we just need to make sure that these changes will not be lost when we migrate it to the rhba jenkins.

2020-06-02 07:17 UTC, radtriste commented
IMO, the cleanup is not the responsibility of the Nightly. The cleanup can be done as we want, when we want and where we want.
The Nightly is only responsible for building, testing and deploying.
So I would go like @Kaitou786 suggested in a separate job. We could then customize it like we want it.
But it should anyway NOT be called by the nightly orchestrating pipeline. It should remain independent.

2020-06-02 15:09 UTC, Kaitou786 commented
So can we merge this one, after that I'll setup a jenkins job to run this script pointing at this repository?

2020-06-02 16:24 UTC, spolti commented
ok, I'll merge this one., but keep the job on a place that we'll not loose when migrating the Jenkins.;

2020-06-02 16:24 UTC, merged