[BXMSPROD-2064] set untrusted input as intermediate env variable
apache/incubator-kie-kogito-pipelines pull request #999
Opened 2023-06-16 21:26 UTC by lampajr

**JIRA:** https://issues.redhat.com/browse/BXMSPROD-2064

As suggested here: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable setting untrusted input as env variable

2023-06-17 13:09 UTC, radtriste approved these changes

2023-06-17 13:09 UTC, radtriste commented
So putting them as env variable will remove the fact that it could be executed code ?

2023-06-18 08:24 UTC, lampajr commented
> So putting them as env variable will remove the fact that it could be executed code ?

yeah exactly, this is the first suggestion from GitHub doc. 
I already make a test locally and it worked as expected.

2023-06-18 15:00 UTC, shubhbapna requested changes
We need to avoid using `{{ inputs.labels }}` in the script directly and we should set it as an env variable here as well:
https://github.com/kiegroup/kogito-pipelines/blob/main/.ci/actions/parse-labels/action.yml#L26

2023-06-18 15:00 UTC, shubhbapna commented on .ci/actions/backporting/action.yml
> +        body: "**Backport:** $ORIGINAL_PR_URL\r\n\r\n$BODY"
According to the GitHub docs passing the untrusted input directly to the `with` portion of the action is safe:

> This approach is not vulnerable to the injection attack, as the context value is not used to generate a shell script, but is instead passed to the action as an argument

https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-action-instead-of-an-inline-script-recommended

So IMO I don't think we have to add the `env` section here and we can keep it how it was before.

2023-06-19 06:52 UTC, lampajr commented on .ci/actions/backporting/action.yml
> +        body: "**Backport:** $ORIGINAL_PR_URL\r\n\r\n$BODY"
I agree with you @shubhbapna., TBH I added them also here more for readability rather than for need but yeah I can easily revert these changes as well

2023-06-19 06:54 UTC, lampajr commented on .ci/actions/backporting/action.yml
> +        body: "**Backport:** $ORIGINAL_PR_URL\r\n\r\n$BODY"
reverted these changes :)

2023-06-19 12:25 UTC, shubhbapna approved these changes

2023-06-19 12:32 UTC, merged